### ISSUE TITLE
Enrich Hubspot contact records with LMS + H data

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#212]
## What

Currently we calculate a lot of activity data for organizations and push it into Hubspot. It would be useful to do something similar for contacts in LMS.

This would include:

 * Are they a public H or LMS user?
 * What roles do they have in LMS?
 * What activity are they associated with in this and previous years / semesters

For more details see: https://docs.google.com/document/d/1ZPYKhALTsXDLM57WDriOAMmiymfPhf-SO8DrIZtEvPU/edit#

This would also lend itself to a nice detailed user summary dashboard.

## Why

 * Having some of this data would help automate emails we send to teachers
 * ... _why indeed?_ - Some more info probably needed to flesh out the case here

## Next steps

 * This ticket should be updated with exact requirements from the linked document above
 * We should think about the data in a more tabular way, which might make it easier to summarise
 * It would be good to highlight the point of each piece of info - e.g. This is for email automation, this is for...
 * If we find any that don't have a reason, maybe we've saved ourselves a bit of time?
 * Once we've enumarated the different "why?" cases, we should think about renaming the task to reflect the why, not the how

**Comment by nairiboo** [comment]
In an effort to try to solidify plans moving forward, I'd like to summarise (based on discussions/docs) what next steps are for this and a breakdown of the data we'll provide.

**Identifying the right customer audience**
In order to support the business contact the appropriate users for customer campaigns we need to ensure certain data points are available. This will allow us to focus communications and reduce unnecessary spam.

**What data do we need?**

- Are they a public H or LMS user?
- What roles do they have in LMS?
- What activity are they associated with in this and previous years / semesters (e.g. are they "active" or not)

**Where should the data live?**

- Hubspot; contact records

**Who is the audience of the data?**

- Sales
- Support
- Marketing

Are we agreed this makes sense based on the info we have?

**Comment by jon-betts** [comment]
A couple of random points:

* We normally don't talk about teachers being active, so much as being associated with activity
* Many users will match to more than one record - so I'm guessing we sum the lot?

**Comment by jon-betts** [comment]
Replaced by:

 * https://github.com/hypothesis/product-backlog/issues/1460
